// <auto-generated />
namespace AspNetMvc4._5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Poprawka : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Poprawka));
        
        string IMigrationMetadata.Id
        {
            get { return "201805112151577_Poprawka"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
